scriptencoding utf-8

let s:save_cpoptions = &cpoptions
set cpoptions&vim

function! s:test1()
  let b = bim#new()
  call b.input('k')
  call bim#assert#are_equal('k', b.raw())
  call bim#assert#are_equal('k', b.yomi())
  call bim#assert#are_equal('', b.okuri())
  call bim#assert#are_equal('', b.yomigana())
  call bim#assert#are_equal('', b.okurigana())
  call b.input('y')
  call bim#assert#are_equal('ky', b.raw())
  call bim#assert#are_equal('ky', b.yomi())
  call bim#assert#are_equal('', b.okuri())
  call bim#assert#are_equal('', b.yomigana())
  call bim#assert#are_equal('', b.okurigana())
  call b.input('a')
  call bim#assert#are_equal('kya', b.raw())
  call bim#assert#are_equal('kya', b.yomi())
  call bim#assert#are_equal('', b.okuri())
  call bim#assert#are_equal("\u304D\u3083", b.yomigana())
  call bim#assert#are_equal('', b.okurigana())
  call b.input('k')
  call bim#assert#are_equal('kyak', b.raw())
  call bim#assert#are_equal('kyak', b.yomi())
  call bim#assert#are_equal('', b.okuri())
  call bim#assert#are_equal("\u304D\u3083", b.yomigana())
  call bim#assert#are_equal('', b.okurigana())
  call b.input('u')
  call bim#assert#are_equal('kyaku', b.raw())
  call bim#assert#are_equal('kyaku', b.yomi())
  call bim#assert#are_equal('', b.okuri())
  call bim#assert#are_equal("\u304D\u3083\u304F", b.yomigana())
  call bim#assert#are_equal('', b.okurigana())
endfunction

function! s:test2()
  let b = bim#new()
  call b.input('w')
  call b.input('a')
  call b.input('s')
  call b.input('u')
  call bim#assert#are_equal(b.raw(), 'wasu')
  call bim#assert#are_equal(b.yomigana(), "\u308F\u3059")
  call bim#assert#is_empty(b.candidate())
  call b.start_okuri()
  call b.input('r')
  call bim#assert#are_equal(b.raw(), 'wasur')
  call bim#assert#are_equal(b.yomi(), 'wasu')
  call bim#assert#are_equal(b.okuri(), 'r')
  call bim#assert#are_equal(b.yomigana(), "\u308F\u3059")
  call bim#assert#are_equal(b.okurigana(), '')
endfunction

function! s:test3()
  let b = bim#new()
  call b.input('a')
  call b.input('i')
  " for c in b.candidate()
  "   call b.convert()
  "   call bim#assert#are_equal(c, b.kanji())
  " endfor
  " call b.convert()
  " call bim#assert#are_equal(b.candidate()[0], b.kanji())
endfunction

function! s:test4()
  let b = bim#new()
  call b.input('k')
  call b.input('a')
  call b.input('n')
  call bim#assert#are_equal('kan', b.raw())
  call bim#assert#are_equal('kan', b.yomi())
  call bim#assert#are_equal('n', b.yomirest())
  call bim#assert#are_equal('', b.okuri())
  call bim#assert#are_equal('', b.okurirest())
  call bim#assert#are_equal("\u304B", b.yomigana())
  call bim#assert#are_equal('', b.okurigana())
  call b.start_okuri()
  call bim#assert#are_equal('kan', b.yomi())
  call bim#assert#are_equal('', b.okuri())
  call bim#assert#are_equal("\u304B\u3093", b.yomigana())
  call bim#assert#are_equal('', b.okurigana())
  call bim#assert#are_equal('', b.okurirest())
  call bim#assert#are_equal('', b.yomirest())
endfunction

function! s:test5()
  let b = bim#new()
  call b.input('k')
  call b.input('a')
  call bim#assert#are_equal('ka', b.raw())
  call bim#assert#are_equal('ka', b.yomi())
  call bim#assert#are_equal('', b.okuri())
  call bim#assert#are_equal("\u304B", b.yomigana())
  call bim#assert#are_equal('', b.okurigana())
  call bim#assert#are_equal('', b.yomirest())
  call bim#assert#are_equal('', b.okurirest())
endfunction

function! s:test6()
  let b = bim#new()
  call b.input('k')
  call b.input('a')
  call b.input('n')
  call bim#assert#are_equal('kan', b.raw())
  call bim#assert#are_equal('kan', b.yomi())
  call bim#assert#are_equal('', b.okuri())
  call bim#assert#are_equal("\u304B", b.yomigana())
  call bim#assert#are_equal('', b.okurigana())
  call bim#assert#are_equal('n', b.yomirest())
  call bim#assert#are_equal('', b.okurirest())
endfunction

function! s:test7()
  let b = bim#new()
  call b.input('k')
  call b.input('a')
  call b.input('n')
  call b.input('j')
  call bim#assert#are_equal('kanj', b.raw())
  call bim#assert#are_equal('kanj', b.yomi())
  call bim#assert#are_equal('', b.okuri())
  call bim#assert#are_equal("\u304B\u3093", b.yomigana())
  call bim#assert#are_equal('', b.okurigana())
  call bim#assert#are_equal('j', b.yomirest())
  call bim#assert#are_equal('', b.okurirest())
endfunction

function! s:test8()
  let b = bim#new()
  call b.input('k')
  call b.input('a')
  call b.input('n')
  call b.input('j')
  call b.input('i')
  call bim#assert#are_equal('kanji', b.raw())
  call bim#assert#are_equal('kanji', b.yomi())
  call bim#assert#are_equal('', b.okuri())
  call bim#assert#are_equal("\u304B\u3093\u3058", b.yomigana())
  call bim#assert#are_equal('', b.okurigana())
  call bim#assert#are_equal('', b.yomirest())
  call bim#assert#are_equal('', b.okurirest())
endfunction

function! s:test9()
  let b = bim#new()
  call b.input('i')
  call b.start_okuri()
  call b.input('u')
  call bim#assert#are_equal('iu', b.raw())
  call bim#assert#are_equal('i', b.yomi())
  call bim#assert#are_equal('u', b.okuri())
  call bim#assert#are_equal("\u3044", b.yomigana())
  call bim#assert#are_equal("\u3046", b.okurigana())
  call bim#assert#are_equal('', b.yomirest())
  call bim#assert#are_equal('', b.okurirest())
endfunction

function! s:test10()
  let b = bim#new()
  call b.input('k')
  call bim#assert#are_equal('k', b.raw())
  call bim#assert#are_equal('k', b.yomi())
  call bim#assert#are_equal('', b.okuri())
  call bim#assert#are_equal('', b.yomigana())
  call bim#assert#are_equal('', b.okurigana())
  call bim#assert#are_equal('k', b.yomirest())
  call bim#assert#are_equal('', b.okurirest())
endfunction

function! s:test()
  call s:test1()
  call s:test2()
  call s:test3()
  call s:test4()
  call s:test5()
  call s:test6()
  call s:test7()
  call s:test8()
  call s:test9()
  call s:test10()
endfunction

call s:test()

let &cpoptions = s:save_cpoptions
unlet! s:save_cpoptions

